title: "Noora Saeed Alhajeri"
description: "Creative Technologist · Robotics Researcher · Designer"
baseurl: ""
url: "https://noora-alhajeri.github.io"

# folders to include in the build
include:
  - _pages
  - _includes
  - _layouts
  - _sass
  - assets

# markdown & build options
markdown: kramdown
highlighter: rouge
theme: minima

sass:
  sass_dir: _sass
  style: compressed

# defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# site metadata for footer and SEO
author:
  name: "Noora Saeed Alhajeri"
  email: "reach.noora@gmail.com"
  github: "Noora-Alhajeri"
  linkedin: "nsh019"
  scholar: "https://scholar.google.com/citations?user=gtA5QBcAAAAJ"

timezone: Asia/Dubai
